/// <reference lib="webworker" />

import {precacheAndRoute} from 'workbox-precaching';
import {registerRoute} from 'workbox-routing';
import {NetworkFirst} from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

// Pre-cache all the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST || []);

// Set up a NetworkFirst caching strategy for navigation requests.
registerRoute(
  ({request}) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [
      // Ensure that navigation requests are cached only if they are successful.
    ],
  })
);

// You can add more caching strategies for other asset types here.
// For example, for CSS, JS, and images.
registerRoute(
  ({request}) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'image',
  new NetworkFirst({
    cacheName: 'assets',
    plugins: [
      // Ensure that assets are cached only if they are successful.
    ],
  })
);
